name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    uses: ./.github/workflows/build.yml@${{github.sha}}
    
  unit-test:
    needs:
      - build
    uses: ./.github/workflows/unit-test.yml@${{github.sha}}
    
  integration-test:
    needs:
      - build
    uses: ./.github/workflows/integration-test.yml@${{github.sha}}
  
  sonarqube-analysis:
    needs:
      - unit-test
      - integration-test
    uses: ./.github/workflows/sonarqube-analysis.yml@${{github.sha}}