name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:  
  sonarqube-analysis:
    uses: ./.github/workflows/sonarqube-analysis.yml
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}