name: SonarQube Analysis

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  analyze:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # 1) Java potrzebne do działania Sonara
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      # 2) Checkout kodu
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 3) .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # 4) Cache pakietów SonarCloud
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # 5) Cache SonarCloud scanner
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner-${{ hashFiles('**/sonar-project.properties') }}
          restore-keys: ${{ runner.os }}-sonar-scanner-

      # 6) Instalacja skanera, jeśli nie ma w cache
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool install dotnet-sonarscanner --version 5.* --tool-path ./.sonar/scanner

      # 7) Begin SonarCloud analysis
      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin \
            /k:"FreakyF_Cryptie" \
            /o:"freakyf" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            # wildcard łapie coverage.opencover.xml w każdym podfolderze TestResults
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
            /d:sonar.verbose=true

      # 8) Build dla Roslyn analyzers
      - name: Build project
        run: dotnet build src/Cryptie.sln --no-incremental

      # 9) Run tests with XPlat Code Coverage
      #    – jednorazowe, poprawne wywołanie dotnet test
      #    – continue-on-error, żeby nawet przy regresji dotrzeć do Sonara
      - name: Run tests with coverage
        continue-on-error: true
        run: |
          dotnet test src/Cryptie.sln \
            --no-build \
            -r linux-x64 \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      # 10) End SonarCloud analysis – odpali się zawsze
      - name: End SonarCloud analysis
        if: always()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner end \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
